#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Generate IT Handoff Document
#
# Auto-generates docs/deployment-guide.md from project state.
# Reads CLAUDE.md, requirements.txt, .env.local to produce a
# complete setup guide for IT teams to deploy to Vercel + Supabase Cloud.
#
# Usage: bash .claude/scripts/generate-handoff-doc.sh
# ─────────────────────────────────────────────────────────────

echo ""
echo "═══════════════════════════════════════════════════════════"
echo " Generating IT Handoff Document"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Extract app name from CLAUDE.md
APP_NAME="[APP_NAME]"
if [ -f "CLAUDE.md" ]; then
    EXTRACTED=$(grep -m1 "^## Project:" CLAUDE.md 2>/dev/null | sed 's/## Project: //' || true)
    if [[ -n "$EXTRACTED" && "$EXTRACTED" != "[APP_NAME]" ]]; then
        APP_NAME="$EXTRACTED"
    fi
fi

# Extract Python deps
PYTHON_DEPS=""
if [ -f "backend/requirements.txt" ]; then
    PYTHON_DEPS=$(cat backend/requirements.txt)
fi

# Extract env var names from .env.local
ENV_VARS=""
if [ -f ".env.local" ]; then
    ENV_VARS=$(grep -E "^[A-Z_]+" .env.local | cut -d= -f1 || true)
fi

# Extract frontend env vars
FRONTEND_ENV_VARS=""
if [ -f "frontend/.env" ]; then
    FRONTEND_ENV_VARS=$(grep -E "^[A-Z_]+" frontend/.env | cut -d= -f1 || true)
fi

mkdir -p docs

cat > docs/deployment-guide.md << DOCEOF
# Deployment Guide — $APP_NAME

> Auto-generated by Sprout toolkit on $(date '+%Y-%m-%d %H:%M:%S').
> This guide helps your IT team deploy the application to Vercel + Supabase Cloud.

---

## Architecture Overview

\`\`\`
┌─────────────────────────────────────────────────┐
│                   Vercel                          │
│                                                   │
│  ┌─────────────────────────────────────────┐    │
│  │  Nuxt 3 SSR (frontend/)                 │    │
│  │  + FastAPI Serverless (api/index.py)     │    │
│  └─────────────────────────────────────────┘    │
│                                                   │
│  Preview deploys per PR                          │
│  Production deploy on merge to main              │
└─────────────────────────────────────────────────┘
                        │
                        ▼
┌─────────────────────────────────────────────────┐
│              Supabase Cloud                       │
│                                                   │
│  PostgreSQL (RLS)  │  Auth (JWT)  │  Storage     │
│  Realtime          │  Edge Funcs  │  Vault       │
└─────────────────────────────────────────────────┘
\`\`\`

---

## 1. Vercel Setup

### Create Team & Import Repository

1. Go to [vercel.com](https://vercel.com) → Create a new Team
2. Enable SSO/SAML if using enterprise identity provider
3. Import this Git repository
4. Vercel will auto-detect the Nuxt 3 framework
5. Set the **Root Directory** to \`.\` (project root)
6. Set the **Build Command** to \`cd frontend && npm run build\`
7. Set the **Output Directory** to \`frontend/.output\`

### Enable Deployment Protection

1. Go to Project Settings → Deployment Protection
2. Enable **Vercel Authentication** for preview deployments
3. Only production deploys should be publicly accessible

### Set Environment Variables

In Vercel Project Settings → Environment Variables, add:

| Variable | Environment | Value |
|----------|-------------|-------|
| \`SUPABASE_URL\` | All | Your Supabase project URL |
| \`SUPABASE_ANON_KEY\` | All | Supabase anon/public key |
| \`SUPABASE_SERVICE_ROLE_KEY\` | All | Supabase service role key |
| \`NUXT_PUBLIC_SUPABASE_URL\` | All | Same as SUPABASE_URL |
| \`NUXT_PUBLIC_SUPABASE_ANON_KEY\` | All | Same as SUPABASE_ANON_KEY |
| \`NUXT_PUBLIC_API_BASE_URL\` | Production | \`https://your-domain.vercel.app/api\` |
| \`PRODUCTION_URL\` | Production | \`https://your-domain.vercel.app\` |
| \`APP_NAME\` | All | $APP_NAME |

> **Security:** \`SUPABASE_SERVICE_ROLE_KEY\` is used by the backend API only. It bypasses Row Level Security and must never be exposed to the client.

---

## 2. Supabase Cloud Setup

### Create Project

1. Go to [supabase.com](https://supabase.com) → Create a new project
2. Choose **Pro** plan (recommended) or **Enterprise** for SOC2/HIPAA compliance
3. Select the region closest to your users
4. Save the project URL and API keys

### Apply Migrations

From the developer's local machine:

\`\`\`bash
# Link to your cloud project
supabase link --project-ref YOUR_PROJECT_REF

# Push all migrations
supabase db push

# Verify
supabase db lint
\`\`\`

### Configure Database Branching (Optional)

For staging/preview environments:

1. Go to Supabase Dashboard → Branching (Pro plan required)
2. Enable branching for preview deploy testing
3. Each PR gets its own database branch

---

## 3. Environment Variables — Complete Mapping

### Backend (.env.local → Vercel)

| Local Variable | Vercel Variable | Notes |
|---------------|-----------------|-------|
$(echo "$ENV_VARS" | while read -r var; do
    [[ -z "$var" ]] && continue
    echo "| \`$var\` | \`$var\` | Set in Vercel dashboard |"
done)

### Frontend (frontend/.env → Vercel)

| Local Variable | Vercel Variable | Notes |
|---------------|-----------------|-------|
$(echo "$FRONTEND_ENV_VARS" | while read -r var; do
    [[ -z "$var" ]] && continue
    echo "| \`$var\` | \`$var\` | Set in Vercel dashboard |"
done)

---

## 4. Security Checklist

- [ ] Deployment protection enabled on Vercel (preview deploys require auth)
- [ ] All environment variables set in Vercel dashboard (no secrets in code)
- [ ] \`SUPABASE_SERVICE_ROLE_KEY\` only in backend environment, not frontend
- [ ] Row Level Security (RLS) enabled on all Supabase tables
- [ ] CORS configured to allow only the production domain
- [ ] HTTPS enforced (Vercel provides this automatically)
- [ ] Security headers configured in \`vercel.json\` (X-Content-Type-Options, X-Frame-Options, HSTS)
- [ ] Supabase database password is strong and unique
- [ ] Supabase Auth email templates customized (no default branding)
- [ ] Rate limiting configured on auth endpoints

---

## 5. Monitoring & Rollback

### Monitoring

- **Vercel Dashboard:** Deployment logs, function invocations, error rates
- **Supabase Studio:** Database queries, auth events, storage usage, realtime connections
- **Logs:** Vercel → Logs tab shows serverless function output (structured JSON)

### Rollback

If a deployment causes issues:

\`\`\`bash
# Option 1: Revert in Vercel dashboard
# Go to Deployments → select previous deployment → Promote to Production

# Option 2: Git revert
git revert HEAD
git push origin main
# Vercel auto-deploys the revert
\`\`\`

### Database Rollback

> **Important:** Database migrations cannot be automatically reverted. Always test migrations on a branch database first.

---

## 6. Branch Strategy

\`\`\`
feature-branch ──▶ PR (preview deploy + branch DB) ──▶ main (production deploy)
\`\`\`

- **Preview deploys:** Every PR gets a unique URL for testing
- **Production deploys:** Only on merge to \`main\`
- **Database branching:** Enable in Supabase for isolated testing per PR

---

## Python Dependencies

\`\`\`
$PYTHON_DEPS
\`\`\`

---

## Support

If you encounter issues during setup:
1. Check Vercel build logs for frontend/API errors
2. Check Supabase logs for database/auth issues
3. Verify all environment variables are set correctly
4. Ensure migrations have been applied to the cloud database
DOCEOF

echo "  Generated: docs/deployment-guide.md"
echo ""
echo "  Share this file with your IT team."
echo ""
