#!/usr/bin/env bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Setup Supabase Cloud — Links local project to Supabase Cloud
#
# Handles local → cloud migration:
#   1. Links local Supabase project to cloud
#   2. Pushes all migrations
#   3. Runs lint verification
#   4. Outputs cloud URL and keys for Vercel env setup
#   5. Generates .env.production (gitignored)
#
# Usage: bash .claude/scripts/setup-supabase-cloud.sh <project-ref>
# ─────────────────────────────────────────────────────────────

PROJECT_REF="${1:-}"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo " Supabase Cloud Setup"
echo "═══════════════════════════════════════════════════════════"
echo ""

# ── 1. Pre-flight checks ─────────────────────────────────────

if ! command -v supabase &>/dev/null; then
    echo "  ERROR: Supabase CLI not found."
    echo "  Install: https://supabase.com/docs/guides/cli"
    exit 1
fi

if [[ -z "$PROJECT_REF" ]]; then
    echo "  ERROR: Project reference required."
    echo ""
    echo "  Usage: bash .claude/scripts/setup-supabase-cloud.sh <project-ref>"
    echo ""
    echo "  Find your project ref in:"
    echo "    Supabase Dashboard → Project Settings → General → Reference ID"
    echo ""
    exit 1
fi

# ── 2. Link to cloud project ─────────────────────────────────

echo "  Linking to Supabase project: $PROJECT_REF"

# Check if already linked
if [ -f "supabase/.temp/project-ref" ]; then
    CURRENT_REF=$(cat "supabase/.temp/project-ref" 2>/dev/null || true)
    if [[ "$CURRENT_REF" == "$PROJECT_REF" ]]; then
        echo "  Already linked to $PROJECT_REF"
    else
        echo "  Re-linking from $CURRENT_REF to $PROJECT_REF"
        supabase link --project-ref "$PROJECT_REF" 2>&1 | tail -5
    fi
else
    supabase link --project-ref "$PROJECT_REF" 2>&1 | tail -5
fi

echo "  Linked successfully."
echo ""

# ── 3. Push migrations ───────────────────────────────────────

echo "  Pushing migrations to cloud..."

MIGRATION_COUNT=$(find supabase/migrations -name "*.sql" 2>/dev/null | wc -l | tr -d ' ')
if [[ "$MIGRATION_COUNT" -eq 0 ]]; then
    echo "  No migrations found — skipping push."
else
    echo "  Found $MIGRATION_COUNT migration(s)."
    supabase db push 2>&1 | tail -10
    echo "  Migrations applied."
fi

echo ""

# ── 4. Lint verification ─────────────────────────────────────

echo "  Running database lint..."
LINT_OUTPUT=$(supabase db lint 2>&1 || true)
LINT_ISSUES=$(echo "$LINT_OUTPUT" | grep -c "ERROR\|WARNING" || true)

if [[ "$LINT_ISSUES" -gt 0 ]]; then
    echo "  WARNING: Database lint found $LINT_ISSUES issue(s):"
    echo "$LINT_OUTPUT" | grep "ERROR\|WARNING" | head -10
else
    echo "  Database lint: clean"
fi

echo ""

# ── 5. Extract cloud credentials ─────────────────────────────

echo "  Extracting cloud credentials..."

# Get project URL and keys from supabase status or project ref
CLOUD_URL="https://${PROJECT_REF}.supabase.co"
echo "  Cloud URL: $CLOUD_URL"
echo ""

# Note: API keys need to be retrieved from the Supabase dashboard
echo "  To get your API keys:"
echo "    1. Go to Supabase Dashboard → Project Settings → API"
echo "    2. Copy the 'anon public' key → SUPABASE_ANON_KEY"
echo "    3. Copy the 'service_role secret' key → SUPABASE_SERVICE_ROLE_KEY"
echo ""

# ── 6. Generate .env.production ───────────────────────────────

cat > .env.production << ENVEOF
# Supabase Cloud credentials (auto-generated by setup-supabase-cloud.sh)
# IMPORTANT: This file is gitignored. Set these values in your Vercel dashboard.
SUPABASE_URL=$CLOUD_URL
SUPABASE_ANON_KEY=<paste-anon-key-from-dashboard>
SUPABASE_SERVICE_ROLE_KEY=<paste-service-role-key-from-dashboard>
NUXT_PUBLIC_SUPABASE_URL=$CLOUD_URL
NUXT_PUBLIC_SUPABASE_ANON_KEY=<paste-anon-key-from-dashboard>
NUXT_PUBLIC_API_BASE_URL=<your-vercel-deployment-url>/api
PRODUCTION_URL=<your-vercel-deployment-url>
APP_NAME=${APP_NAME:-Sprout App}
ENVEOF

echo "  Generated .env.production (gitignored)"
echo "  Fill in the API keys from your Supabase dashboard."
echo ""

# ── 7. Update deploy state ───────────────────────────────────

if [ -f ".claude/deploy-state.json" ] && command -v python3 &>/dev/null; then
    python3 -c "
import json
with open('.claude/deploy-state.json') as f: state = json.load(f)
state['cloud'] = state.get('cloud', {})
state['cloud']['supabase_project_ref'] = '$PROJECT_REF'
with open('.claude/deploy-state.json', 'w') as f: json.dump(state, f, indent=2); f.write('\n')
"
    echo "  Updated .claude/deploy-state.json with project ref."
fi

echo ""
echo "═══════════════════════════════════════════════════════════"
echo " Supabase Cloud setup complete"
echo ""
echo " Cloud URL:  $CLOUD_URL"
echo " Project:    $PROJECT_REF"
echo ""
echo " Next steps:"
echo "   1. Copy API keys from Supabase Dashboard → .env.production"
echo "   2. Set the same keys in Vercel → Environment Variables"
echo "   3. Run: bash .claude/scripts/deploy-cloud.sh production"
echo "═══════════════════════════════════════════════════════════"
echo ""
